feat: marketplace links in NFT details page
ArdentHQ/dashbrd pull request #111
Opened 2023-09-20 11:02 UTC by patricio0312rev

# [[nfts] Add marketplace links to NFTs](https://app.clickup.com/t/861nam1a8)

## Summary

- Marketplaces' URLs have been added to NFT details page.
- New URLs have been added to `urls.php`.
- New `Marketplaces` component has been created, it supports the URL's for `nfts` and `collections`.
- Tests for this new component.

https://github.com/ArdentHQ/dashbrd/assets/55117912/d347f7c5-f788-4174-9260-6b5ad5ae82e6

## Steps to reproduce

1. Run the app in `test_e2e` mode. Make sure you have connected a wallet with collections for both ethereum and polygon.
2. Go to `/collections` page.
3. Select any collection and click on any of its NFTs.
4. You can start clicking on the marketplace icons and see the magic ✨ 

## Checklist

-   [ ] I checked my UI changes against the design and there are no notable differences
-   [ ] I checked my UI changes for any responsiveness issues
-   [ ] I checked my (code) changes for obvious issues, debug statements and commented code
-   [ ] I opened a corresponding card on Clickup for any remaining TODOs in my code
-   [ ] I added a short description on how to test this PR _(if necessary)_
-   [ ] I added a storybook entry for the component that was added _(if necessary)_
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

2023-09-20 19:23 UTC, samharperpittam requested changes
@patricio0312rev - quick on this PR.

The task states " In case there isn't that collection listed there we can assume NFT isn't either so in that case we hide that marketplace from the view."

Though, I'm looking at a collection called `hwape_com`.

I have all marketplace links
<img width="490" alt="image" src="https://github.com/ArdentHQ/dashbrd/assets/44671015/e8659515-2f9a-482a-813f-6d7c64cdcf04">

However, the collection doesn't exist on OpenSea or LooksRare as far as I can tell.

Opensea
<img width="1140" alt="image" src="https://github.com/ArdentHQ/dashbrd/assets/44671015/86a0d650-edd5-4852-8bf9-a71d26f02e42">


Looksrare
<img width="780" alt="image" src="https://github.com/ArdentHQ/dashbrd/assets/44671015/a34f59ba-2385-41d7-bd12-a10991dd2451">

Is the logic for hiding marketplaces missing?

2023-09-26 10:14 UTC, ItsANameToo requested changes
important note: this requires to rerun the `FetchCollectionsMetaData` job for existing collections, otherwise they will not show any marketplace details until the next time it triggers

2023-09-26 10:14 UTC, ItsANameToo commented on app/Data/Collections/CollectionDetailData.php
> +            openSeaSlugUpdatedAt: $collection->extra_attributes->get('opensea_slug_updated_at'),
what is this used for?

2023-10-02 15:28 UTC, ItsANameToo approved these changes

2023-10-02 15:28 UTC, merged