refactor: batch nft metadata requests
ArdentHQ/dashbrd pull request #128
Opened 2023-09-22 13:00 UTC by goga-m

## Summary
Closes https://app.clickup.com/t/861nbbcj7

### Logic
Two new timestamp columns are introduced in nfts table: `metadata_requested_at` and `metadata_fetched_at`, to determine if an nft requires a metadata update. 

When a user clicks to update an nft metadata, `metadata_requested_at` timestamp is set, to indicate that the request is pending. Subsequently `RefreshNftMetadata` job checks for nfts that have the `metadata_requested_at` set and greater than `metadata_fetched_at` and performs a batch nft metadata update for those. It aborts if none is found.

### For testing
#### Single nft (metadata timestamp fields)
1. Comment out the rate limiter in https://github.com/ArdentHQ/dashbrd/blob/develop/app/Providers/AppServiceProvider.php#L66
2. Start the app (make sure horizon is running)
3. Navigate to an nft and click the "refresh metadata" button.
4. Check the particular nft in the database and see the `medadata_requested_at` and `metadata_fetched_at` fields to be set after a few seconds, with `metadata_fetched_at` to be later than `medadata_requested_at`.

#### Multple nft (metadata timestamp fields for multple nfts in one call)
1. Comment out again the rate limiter in https://github.com/ArdentHQ/dashbrd/blob/develop/app/Providers/AppServiceProvider.php#L66
2. Start the app without horizon.
3. Navigate to a few nft pages and click the "refresh metadata" button.
4. You will see that the `metadata_requested_at` field is filled for those nfts in the database.
5. Now start horizon and go to a new nft page and click to refresh metadata.
4. Check all the above nfts to see the `metadata_fetched_at` field to be filled in the database.

## Checklist

-   [ ] I checked my UI changes against the design and there are no notable differences
-   [ ] I checked my UI changes for any responsiveness issues
-   [ ] I checked my (code) changes for obvious issues, debug statements and commented code
-   [ ] I opened a corresponding card on Clickup for any remaining TODOs in my code
-   [ ] I added a short description on how to test this PR _(if necessary)_
-   [ ] I added a storybook entry for the component that was added _(if necessary)_
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [x] Ready to be merged

2023-10-04 11:44 UTC, shahin-hq commented on app/Http/Client/Alchemy/AlchemyPendingRequest.php
> +    public function nftMetadata(Collection $nfts, CollectionModel $collection): Web3NftsChunk
As we discussed in the Slack: 
`CollectionModel $collection`  needs to be replaced by `Network $network`

2023-10-04 11:47 UTC, shahin-hq commented on app/Jobs/RefreshNftMetadata.php
> +        $nfts = Nft::whereNotNull('metadata_requested_at')
As we discussed in the Slack: 
We need to get NFTs grouped by network as we need to request metadata for NFTs on the same network

2023-10-04 11:48 UTC, shahin-hq commented on app/Jobs/RefreshNftMetadata.php
>          if (SpamContract::isSpam($this->collection->address, $this->collection->network)) {
This call should be moved to the controller to prevent queuing metadata requests for unrelated collections.

2023-10-11 01:43 UTC, oXtxNt9U requested changes
@goga-m Left one comment

@shahin-hq Can you check the remaining open threads?

2023-10-11 01:43 UTC, oXtxNt9U commented on app/Http/Client/Alchemy/AlchemyPendingRequest.php
> +    public function nftMetadata(Collection $nfts, Network $network): Web3NftsChunk
Can we rename it to `nftMetadataBatch` ?

2023-10-11 08:47 UTC, shahin-hq approved these changes

2023-10-11 08:59 UTC, oXtxNt9U approved these changes

2023-10-11 19:41 UTC, ItsANameToo approved these changes

2023-10-11 19:41 UTC, merged

2023-10-12 00:59 UTC, oXtxNt9U commented on app/Http/Client/Alchemy/AlchemyPendingRequest.php
> +                return $this->parseNft($nft, $network->id, convertTokenNumber: false);
https://docs.alchemy.com/reference/nft-api-v2-to-v3-migration-guide

> Decimal String token IDs: All token IDs are now served as decimal strings. In V2, token IDs were sometimes served as hexadecimal or decimal strings, which could lead to confusion and potential errors.