feat: add article card
ArdentHQ/dashbrd pull request #149
Opened 2023-09-26 19:01 UTC by shahin-hq

## Summary

## Checklist

-   [ ] I checked my UI changes against the design and there are no notable differences
-   [ ] I checked my UI changes for any responsiveness issues
-   [ ] I checked my (code) changes for obvious issues, debug statements and commented code
-   [ ] I opened a corresponding card on Clickup for any remaining TODOs in my code
-   [ ] I added a short description on how to test this PR _(if necessary)_
-   [ ] I added a storybook entry for the component that was added _(if necessary)_
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

2023-09-26 19:15 UTC, alfonsobries commented on resources/js/Pages/Articles/Components/ArticleCard.tsx
> +        {collections.slice(0, 15).map((collection, index) => (
max amount is 8 I think

2023-09-27 10:50 UTC, ItsANameToo commented
now that https://github.com/ArdentHQ/dashbrd/pull/144 is merged, this can be combined with those implemented article cards

2023-09-28 11:15 UTC, ItsANameToo requested changes
can you add some variations to storybook so it showcases the available scenarios, e.g.:
- 1 collection (single article card)
- 5 collections (single article card)
- 8 collections (single article card)
- grid with 8 cards where they have various amount of collections to see how it looks in a more real-life scenario

2023-09-29 12:48 UTC, shahin-hq commented
@ItsANameToo I made changes as you suggested:

`ArticleListItem`:

![image](https://github.com/ArdentHQ/dashbrd/assets/132887516/3195c002-8de2-45b8-893c-6511f2c15609)

`ArticleCard`

![image](https://github.com/ArdentHQ/dashbrd/assets/132887516/363d8f70-0875-4108-a4fb-7a5ba88ba0de)

`FeaturedCollections` - as a unit

![image](https://github.com/ArdentHQ/dashbrd/assets/132887516/1d6f9702-79a3-424d-9e91-b2aec32af366)

2023-09-29 13:10 UTC, merged