feat: new header design for collections page
ArdentHQ/dashbrd pull request #171
Opened 2023-10-02 03:32 UTC by patricio0312rev

# [[collections] Update UI of the header with new one](https://app.clickup.com/t/862keba76)

## Summary

- New header design has been added for collections page.
- This header also supports dark mode.
- `cursor-not-allowed` class name has been added for disabled buttons.
- New button to update collection has been added (design only)

<img width="1511" alt="image" src="https://github.com/ArdentHQ/dashbrd/assets/55117912/58ec64bc-e568-4efc-921a-a1de3541a651">

<img width="1508" alt="image" src="https://github.com/ArdentHQ/dashbrd/assets/55117912/649c71f7-f3c2-45dc-a25b-cfa68473304f">

## Steps to reproduce

1. Run the app in `local` or `testing_e2e` mode.
2. Click on `collections` button in the navbar or go to `/collections` page and see the magic ✨ 

## Checklist

-   [ ] I checked my UI changes against the design and there are no notable differences
-   [ ] I checked my UI changes for any responsiveness issues
-   [ ] I checked my (code) changes for obvious issues, debug statements and commented code
-   [ ] I opened a corresponding card on Clickup for any remaining TODOs in my code
-   [ ] I added a short description on how to test this PR _(if necessary)_
-   [ ] I added a storybook entry for the component that was added _(if necessary)_
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

2023-10-02 15:50 UTC, ItsANameToo requested changes

2023-10-02 15:50 UTC, ItsANameToo commented on lang/en/common.php
> +    'refresh_collection_description' => 'You can refresh data every 15 minutes.',
remove the refresh related UI as we don't have that feature implemented yet and it will otherwise block the PR

2023-10-04 09:25 UTC, shahin-hq approved these changes

2023-10-04 09:44 UTC, ItsANameToo approved these changes

2023-10-04 09:44 UTC, merged