fix: persist network filter collection when sorting
ArdentHQ/dashbrd pull request #218
Opened 2023-10-12 14:15 UTC by patricio0312rev

# [[collections] persist network filter selection when sorting](https://app.clickup.com/t/862kfrd4a)

## Summary

- When sorting, we now pass the array of selected network filters. This will keep the network filters active when sorting in the collections' grid and in the collection's table.
- The method to sort has been refactored.

## Steps to reproduce

1. Run the app in `local` or `testing_e2e` mode.
2. Go to `/collections` page.
3. Select any network filter.
4. Sort by any category and see the magic ✨ 

https://github.com/ArdentHQ/dashbrd/assets/55117912/29624d1a-4558-4cb7-b8e3-34d1ef6d3fff

## Checklist

-   [ ] I checked my UI changes against the design and there are no notable differences
-   [ ] I checked my UI changes for any responsiveness issues
-   [ ] I checked my (code) changes for obvious issues, debug statements and commented code
-   [ ] I opened a corresponding card on Clickup for any remaining TODOs in my code
-   [ ] I added a short description on how to test this PR _(if necessary)_
-   [ ] I added a storybook entry for the component that was added _(if necessary)_
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

2023-10-13 12:32 UTC, samharperpittam requested changes
Found a minor issue with this. It's possible to get the Collection page in a state where deselecting all networks in the filter doesn't display all nfts as originally spec'd.

<img width="1478" alt="image" src="https://github.com/ArdentHQ/dashbrd/assets/44671015/860223ea-80f2-485d-ac8c-91fa47fe527d">

To reproduce perform the following steps
- Connect a wallet that contains both Eth and Poly NFTs
- Go to Collections
- Filter the networks by selecting either Poly or Eth
- Click sort button and then select "Sort by Received"
- Deselect the selected network in network filter
- See that not all NFTs are displayed when they should be

2023-10-17 10:49 UTC, samharperpittam approved these changes

2023-10-18 08:58 UTC, crnkovic approved these changes

2023-10-18 09:08 UTC, ItsANameToo approved these changes

2023-10-18 09:08 UTC, merged