feat: article view title and cover
ArdentHQ/dashbrd pull request #224
Opened 2023-10-12 22:51 UTC by alfonsobries

## Summary

Closes https://app.clickup.com/t/8678v0jt6

Note: the ticket doesnt mention the article wrapper but im adding it on this ticket, that should include the background with the patterns but I dont have that image yest. 

If i get the image before merging this pr will add it, otherwise can be handled as a separate task

## Checklist

-   [ ] I checked my UI changes against the design and there are no notable differences
-   [ ] I checked my UI changes for any responsiveness issues
-   [ ] I checked my (code) changes for obvious issues, debug statements and commented code
-   [ ] I opened a corresponding card on Clickup for any remaining TODOs in my code
-   [ ] I added a short description on how to test this PR _(if necessary)_
-   [ ] I added a storybook entry for the component that was added _(if necessary)_
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

2023-10-13 09:36 UTC, ItsANameToo commented
I'll await the background image on this PR, as the border seems too close to the header content right now

2023-10-13 09:36 UTC, ItsANameToo requested changes

2023-10-13 09:36 UTC, ItsANameToo commented on resources/js/Pages/Articles/Show.tsx
> +        <div className="mx-8 -mt-6 pb-6 pt-8 sm:-mt-8 md:px-24 lg:mt-0 lg:overflow-hidden lg:rounded-xl lg:border lg:border-theme-secondary-300">
can you double check the padding as it feels too close to the image compared with the design

2023-10-13 16:48 UTC, alfonsobries commented
@ItsANameToo ✅ added background

2023-10-16 10:42 UTC, ItsANameToo requested changes

2023-10-16 10:42 UTC, ItsANameToo commented on resources/js/Pages/Articles/Show.tsx
> +            <div className="bg-white/20 px-8 pt-8 md:px-24">
@alfonsobries this still has an issue with padding. Design is 1376px wide, while the implementation has padding which brings it down to 1310px.

2023-10-16 10:46 UTC, ItsANameToo commented on resources/js/Pages/Articles/Show.tsx
> +            <div className="bg-white/20 px-8 pt-8 md:px-24">
the content should also be max 1000px wide on desktop

2023-10-16 10:47 UTC, ItsANameToo commented on resources/css/_article.css
> +        @apply bg-[url(../images/articles/article-wrapper-bg.svg)] bg-cover bg-top bg-no-repeat dark:bg-[url(../images/articles/article-wrapper-bg-dark.svg)];
the background image seems to span more height than it does in the design

2023-10-17 15:32 UTC, alfonsobries commented
@ItsANameToo @shahin-hq paddng and bg fixed ✅

2023-10-17 18:43 UTC, merged