refactor: session timeout handling
ArdentHQ/dashbrd pull request #231
Opened 2023-10-13 22:08 UTC by alfonsobries

## Summary

Replaces https://github.com/ArdentHQ/dashbrd/pull/200, closes https://app.clickup.com/t/862kf99rz

As explained on the original pr I cant replicate the issue as the video on the ticket probably becase we now handle the "signed actions" differently: The issue I see is: if you try to do something that requires a signature the request returns a 403 error that could be invisible to the user, for example if you sign your wallet, wait until session expires and you try to like a gallery you will see an error in the console but no indication that something wrong happen in the frontend (other that the count not be updated)

Note: in order to make it work i had to fix some side-effects, so we need to validate that also:

1. Notice a [previous PR that removed axios cancel](https://github.com/ArdentHQ/dashbrd/pull/186) and added an abort controller globally, that was causing issues on the fix that Im implementing here so needed to remove the adjustment also noticed that it was not handling the cancelation which was the reason we added axios-cancel on the first place, so basically I replaced the cancelation with a [different solution](https://www.npmjs.com/package/react-use-cancel-token) (how to test below)
2. once I fixed the request cancelation noticed that the collection page was making two requests to load the collections when opened, meaning double memory usage, also was requesting the collection for guest users, fixed both issues

To test the axios cancel part you need to emulate a canceled request, that is mostly used on the search fields, so for example if a user creates a gallery and searches for a nft, changes the query but the prev search request didnt finished it should cancel the prev request, since is not easy to emulate that you can hardcode `sleep` in the controller that return the response, for example, on the  `app/Http/Controllers/MyGalleryCollectionController.php` you can add `sleep(5)` inside the `index` method. since request is going to be slower if will be canceled while you search (see video)

![image](https://github.com/ArdentHQ/dashbrd/assets/17262776/ff4d052e-38c3-460d-b55f-ee0d6b41d3d8)

https://github.com/ArdentHQ/dashbrd/assets/17262776/1a4862ba-dffc-4a61-8a33-c9b709a005c1

This apply to every component that I updated with `newAbortSignal`, is not easy to explain how to test all of them but if you have issues ping me on slack, 

## Checklist

-   [ ] I checked my UI changes against the design and there are no notable differences
-   [ ] I checked my UI changes for any responsiveness issues
-   [ ] I checked my (code) changes for obvious issues, debug statements and commented code
-   [ ] I opened a corresponding card on Clickup for any remaining TODOs in my code
-   [ ] I added a short description on how to test this PR _(if necessary)_
-   [ ] I added a storybook entry for the component that was added _(if necessary)_
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

2023-10-19 01:35 UTC, oXtxNt9U requested changes
Noticed one issue, otherwise looks fine to me:

- Sign in
- Open 'Create Gallery'
- Delete cookies
- Now instead of getting a dialog, it keeps spamming 401 exceptions
- Once I navigate to a different page I get a dialog


![image](https://github.com/ArdentHQ/dashbrd/assets/120286271/49795072-e3e7-4d03-b89d-db2a80cfe3b3)

2023-10-19 21:39 UTC, alfonsobries commented
@oXtxNt9U fixed

2023-10-20 00:42 UTC, oXtxNt9U approved these changes

2023-10-23 12:03 UTC, crnkovic approved these changes

2023-10-25 11:55 UTC, merged