fix: prevent share buttons overlap
ArdentHQ/dashbrd pull request #260
Opened 2023-10-20 16:07 UTC by alfonsobries

## Summary

https://app.clickup.com/t/862kghv3r

## Checklist

-   [ ] I checked my UI changes against the design and there are no notable differences
-   [ ] I checked my UI changes for any responsiveness issues
-   [ ] I checked my (code) changes for obvious issues, debug statements and commented code
-   [ ] I opened a corresponding card on Clickup for any remaining TODOs in my code
-   [ ] I added a short description on how to test this PR _(if necessary)_
-   [ ] I added a storybook entry for the component that was added _(if necessary)_
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

2023-10-23 08:44 UTC, crnkovic requested changes
If you resize the window so that content is short but the window is scrollable (open the dev tools and expand the height a lot), it seems that this doesn't fix the issue.

https://github.com/ArdentHQ/dashbrd/assets/6536260/6c034629-92ef-476b-9c76-6ccad247169d

2023-10-23 16:50 UTC, alfonsobries commented
@crnkovic fixed ✅

2023-10-24 07:09 UTC, crnkovic approved these changes

2023-10-24 08:05 UTC, ItsANameToo approved these changes

2023-10-24 08:06 UTC, merged