feat: filter unpublished articles
ArdentHQ/dashbrd pull request #262
Opened 2023-10-20 17:00 UTC by alfonsobries

## Summary

Closes https://app.clickup.com/t/8678v0ceb

Doesnt make any change to the admin which already allows to nullify or set the published at in the future, but updates the article controller to filter published articles only

## Checklist

-   [ ] I checked my UI changes against the design and there are no notable differences
-   [ ] I checked my UI changes for any responsiveness issues
-   [ ] I checked my (code) changes for obvious issues, debug statements and commented code
-   [ ] I opened a corresponding card on Clickup for any remaining TODOs in my code
-   [ ] I added a short description on how to test this PR _(if necessary)_
-   [ ] I added a storybook entry for the component that was added _(if necessary)_
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

2023-10-23 08:41 UTC, crnkovic requested changes
LGTM; just seems you missed one other place where we load articles.

2023-10-23 08:41 UTC, crnkovic commented on app/Models/Article.php
> +    public function scopePublished(Builder $query): Builder
There is already a scope called `isPublished()` in this model that only checks for `published_at` being `null` and is used in a [`CollectionController`](https://github.com/ArdentHQ/dashbrd/blob/feat/articles/app/Http/Controllers/CollectionController.php#L262).

Can you just ensure that we can remove that other scope and replace the call in the controller with your scope?

2023-10-23 16:54 UTC, alfonsobries commented
@crnkovic ✅

2023-10-24 07:09 UTC, crnkovic approved these changes

2023-10-24 08:08 UTC, ItsANameToo approved these changes

2023-10-24 08:08 UTC, merged