feat: add manual activity refresh button
ArdentHQ/dashbrd pull request #267
Opened 2023-10-23 11:06 UTC by goga-m

## Summary

Closes https://app.clickup.com/t/862kg5zyr
* Shows collection refresh button when activity tab is clicked.
* When refresh is clicked, a toast message is displayed "Refreshing activity.... Please check back later"
* Prevents from refreshing if the collection has invalid supply (those without or very large supply). The button stays disabled and shows the respective tooltip.
* When a collection has already been updated, it allows one more refresh request, and schedules the job to run after 6 hours. The button goes to disabled state showing the loading message. A new column is added in collections table to handle that scenario: `activity_update_requested_at`.
* User can only update 3 different collections per hour. For simplicity, this feature is implemented client side. We store the collection activity requests in local storage and disable the button when 3 updates were made in the last hour. See https://github.com/ArdentHQ/dashbrd/pull/267/files#diff-d47f3f6de229d25ecaf915061b83c7f3158df91430cf132ef485b1056384b7e8R18

* Updates the entire collection's activity  when clicking refresh button in nft page
## Checklist

-   [ ] I checked my UI changes against the design and there are no notable differences
-   [ ] I checked my UI changes for any responsiveness issues
-   [ ] I checked my (code) changes for obvious issues, debug statements and commented code
-   [ ] I opened a corresponding card on Clickup for any remaining TODOs in my code
-   [ ] I added a short description on how to test this PR _(if necessary)_
-   [ ] I added a storybook entry for the component that was added _(if necessary)_
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

2023-10-25 18:04 UTC, alfonsobries requested changes
its not specified on the ticket but we should require signature to refresh, [see this ](https://github.com/ArdentHQ/dashbrd/pull/183/files/56d677780ac7a12e07e5e0df148aed2fa6e080d7#diff-aa8d5473f1cf28433f02b4fc33b3cdec32cf446c0517a730520293de2dae3140R18-R19) as reference  (mind the comments) also the midleware for signed wallets

2023-10-26 18:29 UTC, alfonsobries requested changes
@goga-m minor adjusment

2023-10-27 16:25 UTC, alfonsobries approved these changes

2023-10-30 02:35 UTC, oXtxNt9U approved these changes
LGTM

2023-10-30 10:21 UTC, merged