refactor: prevent adding NFTs without an image to gallery
ArdentHQ/dashbrd pull request #268
Opened 2023-10-23 12:43 UTC by shahin-hq

## Summary

## Checklist

-   [ ] I checked my UI changes against the design and there are no notable differences
-   [ ] I checked my UI changes for any responsiveness issues
-   [ ] I checked my (code) changes for obvious issues, debug statements and commented code
-   [ ] I opened a corresponding card on Clickup for any remaining TODOs in my code
-   [ ] I added a short description on how to test this PR _(if necessary)_
-   [ ] I added a storybook entry for the component that was added _(if necessary)_
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

2023-10-23 13:31 UTC, shahin-hq commented on resources/js/Components/Image/Image.blocks.tsx
> +export const ImageErrorPlaceholder = ({
typo fix

2023-10-23 14:53 UTC, crnkovic requested changes
LGTM, but can you also add validation to the backend to validate all NFTs have images?

2023-10-24 12:49 UTC, crnkovic approved these changes

2023-10-25 11:41 UTC, ItsANameToo approved these changes

2023-10-25 11:41 UTC, merged