Feat/markdown parsing
ArdentHQ/dashbrd pull request #271
Opened 2023-10-23 21:06 UTC by alfonsobries

## Summary

Uses to parse the markdown

Closes https://app.clickup.com/t/865d922px

The plugin works well in the sense that it seems to parse the content of the test articles correctly. However, the content doesn't appear as we might expect it to. This is more like an issue with the articles that were prepared for MSQ rather than a problem with the parser itself. For example, the articles have images, and it appears that an attempt was made to add a "caption" using the blockquote format `> ...`. In MSQ, this is handled differently, so it appears correctly there, but here, since it's the default format, it generates a lieral blockquote block.

In my opinion, it's fine to leave it as it is because it avoids adding patches or stuff like that which allows us to switch between parsers if necessary. 

The only missing detail is how to add image with caption since doenst seem to be an standard in markdown, so im only making the img with alt (`[alt text](http:/img.url)`) to be parsed as an image with caption instead of an image with alt text as the standard

## Checklist

-   [ ] I checked my UI changes against the design and there are no notable differences
-   [ ] I checked my UI changes for any responsiveness issues
-   [ ] I checked my (code) changes for obvious issues, debug statements and commented code
-   [ ] I opened a corresponding card on Clickup for any remaining TODOs in my code
-   [ ] I added a short description on how to test this PR _(if necessary)_
-   [ ] I added a storybook entry for the component that was added _(if necessary)_
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

2023-10-24 08:37 UTC, ItsANameToo commented on resources/js/Pages/Articles/Components/ArticleContent.tsx
> +    console.log({ article });
:watching:

2023-10-24 08:53 UTC, shahin-hq commented
It looks beautiful. Nice job. :+1: 
My only comment is about links, I think they should open in a new tab by default. Also we might want to have `nofollow`, `noreferrer` attributes on these links.

2023-10-24 09:04 UTC, ItsANameToo requested changes
I updated the articles json to use the markdown alt tag. Issue with that one is that we cannot use links inside of it, which is something they often did for MSQ captions. 

Can you have a look at whether we can make those work in some way to allow links to exist in captions again? I believe that was one of the reasons we went with a custom format on MSQ

2023-10-24 19:34 UTC, alfonsobries commented
Replaced the plugin for converting the img alt text to caption in favour of  a custom plugin that converts blockquotes that are next to images to figure with figcaption

So 

```markdown
![](https://i.imgur.com/kw1vnVD.gif)

> the [pixels](http://link.com/page)
```

become

```html
<figure>
  <img src="https://i.imgur.com/kw1vnVD.gif alt="alt text" style="width:100%">
  <figcaption>the <a href="http://link.com/page">pixels</a></figcaption>
</figure>
```

Also links are now opened in a new tab 

cc @ItsANameToo  @shahin-hq

2023-10-25 09:39 UTC, ItsANameToo approved these changes

2023-10-25 09:39 UTC, merged