refactor: article card hover states
ArdentHQ/dashbrd pull request #280
Opened 2023-10-25 13:45 UTC by crnkovic

## Summary

https://app.clickup.com/t/862kh3hr0

## Checklist

-   [ ] I checked my UI changes against the design and there are no notable differences
-   [ ] I checked my UI changes for any responsiveness issues
-   [ ] I checked my (code) changes for obvious issues, debug statements and commented code
-   [ ] I opened a corresponding card on Clickup for any remaining TODOs in my code
-   [ ] I added a short description on how to test this PR _(if necessary)_
-   [ ] I added a storybook entry for the component that was added _(if necessary)_
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

2023-10-25 16:55 UTC, alfonsobries requested changes
On the slider the border is cropped

![image](https://github.com/ArdentHQ/dashbrd/assets/17262776/d243702a-a56c-4cd5-9aab-f7e05818ee3f)

2023-10-26 09:33 UTC, crnkovic commented
Due to hidden overflow and width/height being managed by Swiper, the most pain-free solution was to add `ring-inset` to add the ring from the inside instead of outside. I don't think anyone will care whether ring is on the outside or inside, so this is what it looks like.

https://github.com/ArdentHQ/dashbrd/assets/6536260/73ca5b00-81be-4c49-9ee7-cdc9e55259ff

2023-10-26 09:58 UTC, ItsANameToo approved these changes

2023-10-26 09:59 UTC, ItsANameToo commented
some conflicts @crnkovic

2023-10-26 10:18 UTC, merged