feat: add articles audio player
ArdentHQ/dashbrd pull request #305
Opened 2023-10-26 21:06 UTC by shahin-hq

## Summary

## Checklist

-   [ ] I checked my UI changes against the design and there are no notable differences
-   [ ] I checked my UI changes for any responsiveness issues
-   [ ] I checked my (code) changes for obvious issues, debug statements and commented code
-   [ ] I opened a corresponding card on Clickup for any remaining TODOs in my code
-   [ ] I added a short description on how to test this PR _(if necessary)_
-   [ ] I added a storybook entry for the component that was added _(if necessary)_
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

2023-10-27 11:58 UTC, crnkovic reviewed
I personally like the wave surfer more, looks sleek! Will see what others say!

I just noticed the tiny color issue for the waves (should be primary-900) and forgotten translations in "Audio Version".

<img width="432" alt="Screenshot 2023-10-27 at 13 56 50" src="https://github.com/ArdentHQ/dashbrd/assets/6536260/17dc0732-d014-48c3-9c7f-87c09906e9e2">

2023-10-31 09:42 UTC, ItsANameToo requested changes
I prefer the wavesurfer one as well, looks good. 

One remark about the loading state for it: the spinner takes up more height than the actual wave it will show and it shifts the content

2023-10-31 09:42 UTC, ItsANameToo commented on resources/icons/audio-play.svg
> +<svg width="20" height="21" viewBox="0 0 20 21" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M12.852 6.67c2.724 1.676 4.085 2.514 4.341 3.68.087.398.087.809 0 1.206-.256 1.166-1.617 2.004-
best to remove width and height and only keep the viewBox so it's possible to use different sizes for the image. Same applies to the other one

2023-10-31 12:36 UTC, ItsANameToo approved these changes

2023-10-31 13:26 UTC, shahin-hq commented on resources/js/Pages/Articles/Components/AudioPlayer.tsx
> +        setCurrentTime(newTime);
Removed :sadup:

2023-10-31 13:38 UTC, merged