feat: my gallery sidebar
ArdentHQ/dashbrd pull request #306
Opened 2023-10-26 21:10 UTC by alfonsobries

## Summary

Closes https://app.clickup.com/t/862kh22ph

## Checklist

-   [ ] I checked my UI changes against the design and there are no notable differences
-   [ ] I checked my UI changes for any responsiveness issues
-   [ ] I checked my (code) changes for obvious issues, debug statements and commented code
-   [ ] I opened a corresponding card on Clickup for any remaining TODOs in my code
-   [ ] I added a short description on how to test this PR _(if necessary)_
-   [ ] I added a storybook entry for the component that was added _(if necessary)_
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

2023-10-27 11:49 UTC, crnkovic requested changes
There's no "Create Gallery" button on desktop on the top right, but there is one on mobile. Was this intentional?

If intentional then ignore, everything else is fine.

<img width="1501" alt="Screenshot 2023-10-27 at 13 49 05" src="https://github.com/ArdentHQ/dashbrd/assets/6536260/41c8c6d1-a6c5-4a98-8722-1266f0ae0aaf">

2023-10-27 13:49 UTC, alfonsobries commented
@crnkovic it was a mistake, should be ok now

2023-10-27 14:30 UTC, crnkovic approved these changes

2023-10-30 10:28 UTC, ItsANameToo approved these changes

2023-10-30 10:28 UTC, merged