refactor: handle gallery drafts on wallet switches
ArdentHQ/dashbrd pull request #376
Opened 2023-11-07 09:17 UTC by shahin-hq

## Summary

## Checklist

-   [ ] I checked my UI changes against the design and there are no notable differences
-   [ ] I checked my UI changes for any responsiveness issues
-   [ ] I checked my (code) changes for obvious issues, debug statements and commented code
-   [ ] I opened a corresponding card on Clickup for any remaining TODOs in my code
-   [ ] I added a short description on how to test this PR _(if necessary)_
-   [ ] I added a storybook entry for the component that was added _(if necessary)_
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

2023-11-07 12:08 UTC, shahin-hq commented on resources/js/Components/Galleries/NftGridEditable.tsx
> +    }, [selectedNftIds]);
We need something stable here, a primitive

2023-11-07 12:09 UTC, shahin-hq commented on resources/js/Pages/Galleries/MyGalleries/Create.tsx
> +    }, [switching]);
Reset stuff when switching

2023-11-07 12:10 UTC, shahin-hq commented on resources/js/Pages/Galleries/MyGalleries/Create.tsx
> +                    key={auth.wallet.address}
Reset selected NFTs when wallet changes

2023-11-07 12:10 UTC, shahin-hq commented on resources/js/Pages/Galleries/hooks/useGalleryDrafts.ts
> +        setDraft((previousDraft) => ({ ...previousDraft, title }));
a sneaky one, should use previous draft over `draft` otherwise unexpected things may happen

2023-11-08 09:28 UTC, ItsANameToo requested changes
overall works well. Only scenario I encountered where it acts odd is the following:
1. have address A with 6 local drafts
2. create a new gallery with address A, set a title and 1 NFT
3. switch to address B in metamask
4. NFT resets as expected, title remains
5. now cancel as address B and look at the drafts
6. this draft is not saved

same happens when you'd add some NFTs from address B in step 4; it doesn't save it as a draft afterwards

2023-11-08 09:29 UTC, ItsANameToo commented
also noticed it will show the wrong drafts when you switch addresses on the overview page, but added a separate card for that https://app.clickup.com/t/86dqhaea2

2023-11-13 13:58 UTC, ItsANameToo commented
in case that same tests fails again @shahin-hq , it was supposed to be fixed with Goga's changes on https://github.com/ArdentHQ/dashbrd/pull/349 🤔

2023-11-13 14:50 UTC, ItsANameToo commented
conflicts @shahin-hq

2023-11-13 20:48 UTC, alfonsobries commented
Conflicts @shahin-hq

2023-11-15 09:26 UTC, shahin-hq commented
Not ready yet:

https://github.com/ArdentHQ/dashbrd/assets/132887516/31ea7a2e-9b3f-4fdc-a76e-cd818e4d2a46

2023-11-15 13:50 UTC, shahin-hq commented on resources/js/Pages/Galleries/MyGalleries/Create.tsx
> +        // Create a new draft, copy title & cover from the existin, add redirect to the new.
should be fine

2023-11-15 14:30 UTC, ItsANameToo approved these changes

2023-11-15 14:35 UTC, merged