fix: refresh activity button styles
ArdentHQ/dashbrd pull request #416
Opened 2023-11-08 18:08 UTC by patricio0312rev

# [[collections] "Refresh" button requires padding within Activity tab](https://app.clickup.com/t/86dqhaj6p)

## Summary

- Padding for the `Refresh` activity button has been fixed.

<img width="1504" alt="image" src="https://github.com/ArdentHQ/dashbrd/assets/55117912/cc7a9945-57c5-49ec-81c7-2d18c6a8c6d4">

- The alignment for the buttons on desktop view has also been fixed.
<img width="1502" alt="image" src="https://github.com/ArdentHQ/dashbrd/assets/55117912/2cbbc7a9-110b-4f51-acd5-f37bd3c8149a">

## Steps to reproduce

- Run the app in `local` or `testing_e2e` mode.
- Make sure your testing wallet has at least 1 NFT.
- Navigate to `/collections` page.
- Select any collection.
- Click on `Activity` tab and see the magic ✨ 

## Checklist

-   [ ] I checked my UI changes against the design and there are no notable differences
-   [ ] I checked my UI changes for any responsiveness issues
-   [ ] I checked my (code) changes for obvious issues, debug statements and commented code
-   [ ] I opened a corresponding card on Clickup for any remaining TODOs in my code
-   [ ] I added a short description on how to test this PR _(if necessary)_
-   [ ] I added a storybook entry for the component that was added _(if necessary)_
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

2023-11-08 23:56 UTC, alfonsobries approved these changes

2023-11-09 09:36 UTC, ItsANameToo requested changes

2023-11-09 09:36 UTC, ItsANameToo commented on resources/js/Pages/Collections/Components/CollectionNavigation/CollectionNavigation.tsx
> +                                        className="hidden h-10 bg-theme-secondary-200 text-theme-primary-900 sm:block"
why is this button larger than `h-10` to begin with? 🤔 might be worth finding the reason that causes that than forcing it to 40 as the secondary button by default should already be 40px

2023-11-10 09:00 UTC, ItsANameToo commented on resources/js/Pages/Collections/Components/CollectionNavigation/CollectionNavigation.tsx
> +                                        className="hidden h-10 bg-theme-secondary-200 text-theme-primary-900 sm:block"
I still see `h-10` here

2023-11-10 09:59 UTC, ItsANameToo approved these changes
also fixed dark mode on the refresh button

2023-11-10 10:12 UTC, merged