feat: add tables, footnotes, striketroughs, and tasklists support for articles
ArdentHQ/dashbrd pull request #439
Opened 2023-11-13 16:11 UTC by patricio0312rev

# [[articles] table and strikethrough markdown not displayed correctly](https://app.clickup.com/t/86dqhwt5a)

## Summary

- `remark-gfm` has been installed and configured as a plugin for `react-markdown`. You can check its docs [here](https://www.npmjs.com/package/remark-gfm).
- As a result, we now support not only tables and strikethroughs, but also `footnotes`, `tasklists` and `autolink literals`.
- Styles for `tasklists` have been updated to match our `checkbox input` styles.

## Steps to reproduce

1. Run the app in `local` mode.
2. Go to `/admin`portal and log in.
3. Click on the `Articles` menu item and either create or edit an existing article.
4. Any of the new supported features can be added. As an example, for tables and striketroughs, we can use:
```
## Strikethrough

~one~ or ~~two~~ tildes.

## Table

| a | b  |  c |  d  |
| - | :- | -: | :-: |
```
5. Go to `/articles` page.
6. Select the article with the new content and see the magic ✨ 

## Screenshots

<img width="658" alt="image" src="https://github.com/ArdentHQ/dashbrd/assets/55117912/517ba323-6cd2-43fc-a150-c3f091701527">

## Checklist

-   [ ] I checked my UI changes against the design and there are no notable differences
-   [ ] I checked my UI changes for any responsiveness issues
-   [ ] I checked my (code) changes for obvious issues, debug statements and commented code
-   [ ] I opened a corresponding card on Clickup for any remaining TODOs in my code
-   [ ] I added a short description on how to test this PR _(if necessary)_
-   [ ] I added a storybook entry for the component that was added _(if necessary)_
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

2023-11-13 20:49 UTC, alfonsobries commented on resources/js/Pages/Articles/Components/ArticleContent.tsx
> +    console.log({ article });
🤔

2023-11-13 20:56 UTC, alfonsobries requested changes
a table with three rows expands the first row

![image](https://github.com/ArdentHQ/dashbrd/assets/17262776/e269b34e-4ab7-4690-b59c-5033638eb578)


I would also modify some articles with different tables so we can easily test

2023-11-14 15:12 UTC, alfonsobries commented
@patricio0312rev the table on one of the examples is not using the whole space,

![image](https://github.com/ArdentHQ/dashbrd/assets/17262776/ca49a158-13b0-4701-9797-04af29acf952)


Other than that 👌

2023-11-14 23:30 UTC, alfonsobries approved these changes

2023-11-15 10:25 UTC, ItsANameToo requested changes
can we add just a table parser? there's no need to implement GFM for the articles as the other aspects aren't used.

Design will also be slightly different for tables than what is currently implemented. Turning this into draft until design is approved

2023-11-15 10:36 UTC, ItsANameToo commented on resources/css/_article.css
> +    @apply pb-8;
this is a very large padding 🤔

2023-11-15 10:40 UTC, ItsANameToo requested changes
some general remarks:
- we should discuss the need for GFM and how it's currently implemented in this PR if we choose to keep it
- some articles were adjusted to include a table (e.g. a TOC) but those link to sections while we don't support anchors, making them contain examples that don't work as intended. We should discuss the need for heading anchors and if needed implement them or adjust the examples to not set false expectations
- tables will need design adjustments, I'll link that on the clickup card

2023-11-17 10:32 UTC, samharperpittam approved these changes

2023-11-17 10:58 UTC, ItsANameToo approved these changes

2023-11-17 10:59 UTC, merged