fix: delete draft if empty when navigating away
ArdentHQ/dashbrd pull request #473
Opened 2023-11-17 15:35 UTC by goga-m

## Summary
Closes https://app.clickup.com/t/86dqk1uey 

## Checklist

-   [ ] I checked my UI changes against the design and there are no notable differences
-   [ ] I checked my UI changes for any responsiveness issues
-   [ ] I checked my (code) changes for obvious issues, debug statements and commented code
-   [ ] I opened a corresponding card on Clickup for any remaining TODOs in my code
-   [ ] I added a short description on how to test this PR _(if necessary)_
-   [ ] I added a storybook entry for the component that was added _(if necessary)_
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [x] Ready to be merged

2023-11-17 17:03 UTC, alfonsobries requested changes
seems that a new bug was introduced on this pr (i cant replicate the error in `rc-0.11.9`)

To test:
1. remove all drafts (this step may not be necessary but was my specific case)
2. create a new gallery and add nfts
3. see that draft saved
4. cancel and see that draft is not stored

https://github.com/ArdentHQ/dashbrd/assets/17262776/4b804c69-c179-486b-857c-6595943813ab

2023-11-20 14:17 UTC, crnkovic approved these changes

2023-11-21 13:29 UTC, samharperpittam approved these changes

2023-11-21 15:25 UTC, alfonsobries approved these changes

2023-11-21 15:28 UTC, merged