refactor: move create gallery components to a new file
ArdentHQ/dashbrd pull request #474
Opened 2023-11-17 15:52 UTC by patricio0312rev

# [[galleries] Move form components to its own file](https://app.clickup.com/t/86dqk0fy9)

## Summary

- `CreateGalleryForm` component has been created. It contains all the components related to the creation of a gallery.
- Almost 100 lines from the `MyGallery/Create` page have been removed.

> Note: The file still requires some optimization regarding the number of hooks and contexts used. Will create a new ticket related to this part.

## Steps to reproduce

1. Run the app in `local` or `testing_e2e` mode.
2. Click on `Create a Gallery` button.
3. Make sure all the components in this zone work correctly and see the magic ✨ 
<img width="1510" alt="image" src="https://github.com/ArdentHQ/dashbrd/assets/55117912/abc5134f-b6fd-46fe-af23-86cb34b0b62f">

## Checklist

-   [ ] I checked my UI changes against the design and there are no notable differences
-   [ ] I checked my UI changes for any responsiveness issues
-   [ ] I checked my (code) changes for obvious issues, debug statements and commented code
-   [ ] I opened a corresponding card on Clickup for any remaining TODOs in my code
-   [ ] I added a short description on how to test this PR _(if necessary)_
-   [ ] I added a storybook entry for the component that was added _(if necessary)_
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

2023-11-21 10:30 UTC, samharperpittam approved these changes

2023-11-21 16:04 UTC, alfonsobries requested changes
the create gallery button is not working (at least) in this scenario

1. set `APP_ENV=testing_e2e`
2. go to create gallery form
3. fill gallery
4. press "Publish"
5. nothing happens, no any kind of feedback

On `develop` I dont have that issue

2023-11-24 17:30 UTC, alfonsobries approved these changes

2023-11-27 10:44 UTC, crnkovic approved these changes

2023-11-27 11:16 UTC, merged