feat: featured collections carousel
ArdentHQ/dashbrd pull request #494
Opened 2023-11-23 14:49 UTC by patricio0312rev

# [[featured collections] add featured collections slider](https://app.clickup.com/t/86dqk1xar)

## Summary

- Featured collections are now being displayed in a hero carousel on `/collections` overview page.
- The NFTs for our Featured collections are being cached and we will update them every 12 hours.
- `NftSeeder` has been updated to add support for `description` and `is_featured` fields. 
- New `CollectionFeaturedData` data type that will be used to get the new data structure for featured collections.
- New entries in our language files to add support for new texts in use.
- The `featured-collections-overlay` class name has been added, to add support for the gradient for our featured collections card's background.
- New prop for `GridHeader`. It now supports custom `wrapperClassNames`.
- `CollectionNft` card now supports custom class names.
- New `FeaturedCollectionsCarousel` and `FeaturedCollectionsItem` components.
- `FormatCrypto` component now supports `maximumFractionDigits`.
- Unit tests have been added for component features.
- The `autoplay` effect has been added to our carousel. It will change the slide every 5 secs.

> NOTE: Changes related to arrows and pagination for the sliders will come in other ticket.

## Steps to reproduce

- Run the app in `local` or `testing_e2e` mode.
- Make sure your testing wallet has some NFTs. Or you can just run `composer db:dev`.
- If you're not running migrations, or if you want to toggle featured collections, go to `/admin` portal.
- Click on `Collections` and mark as `featured` 3 or 4 collections.
   - I recommend to test for: collection with +3 nfts + description, collection with 2 nfts , collection with no description, collection with just 1 nft.
- Save the changes.
- Go to `/collections` page and see the magic ✨ 

https://github.com/ArdentHQ/dashbrd/assets/55117912/e9438a1a-0701-488b-bb3d-eb6ffbeb9ac3

## Checklist

-   [ ] I checked my UI changes against the design and there are no notable differences
-   [ ] I checked my UI changes for any responsiveness issues
-   [ ] I checked my (code) changes for obvious issues, debug statements and commented code
-   [ ] I opened a corresponding card on Clickup for any remaining TODOs in my code
-   [ ] I added a short description on how to test this PR _(if necessary)_
-   [ ] I added a storybook entry for the component that was added _(if necessary)_
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

2023-11-23 16:37 UTC, alfonsobries commented
@patricio0312rev tests

2023-11-24 09:16 UTC, ItsANameToo commented
conflicts @patricio0312rev

2023-11-24 10:33 UTC, ItsANameToo requested changes
- can you also add padding between the featured and popular component as they currently touch
<img width="453" alt="image" src="https://github.com/ArdentHQ/dashbrd/assets/35610748/79554337-bc74-45f6-8b3d-5ca08c6e59dd">
- some conflicts in the meantime as well

2023-11-24 10:33 UTC, ItsANameToo commented on app/Http/Controllers/CollectionController.php
> +            $collection->cachedNfts = Cache::remember('featuredNftsForCollection'.$collection->id, 60 * 12, function () use ($collection) {
isn't the cache in seconds? e.g. 60 * 12 would be 12 minutes instead of hours 🤔

2023-11-24 10:33 UTC, ItsANameToo commented on resources/js/Pages/Collections/Components/FeaturedCollections/FeaturedCollectionsItem.tsx
> +                            </div>
I noticed the popular collections table also uses a component like this, can it be combined so we can reuse it where needed instead
<img width="187" alt="image" src="https://github.com/ArdentHQ/dashbrd/assets/35610748/d8861700-fd19-440c-8f11-45dde857a7c5">

2023-11-24 10:33 UTC, ItsANameToo commented on resources/js/Pages/Collections/Components/FeaturedCollections/FeaturedCollectionsItem.tsx
> +                            />
for readability it might be nice to move this to a component, but let me know what you think

2023-11-24 10:33 UTC, ItsANameToo commented on resources/js/Pages/Collections/Components/FeaturedCollections/FeaturedCollectionsItem.tsx
> +                </div>
likewise here for readability

2023-11-24 10:33 UTC, ItsANameToo commented on resources/js/Pages/Collections/Components/FeaturedCollections/FeaturedCollectionsItem.tsx
> +    }
personally I'd change the check as follows:
```suggestion
    if (description !== null && description.length > 120) {
        return description.slice(0, 117) + "...";
    }
```

that way you don't end up with 120 characters + 3 additional ones or the weird scenario where you'd have a 121-123 character description that would be truncated but take up the same amount of width due to the `...` being added

2023-11-24 12:07 UTC, ItsANameToo approved these changes

2023-11-24 12:18 UTC, samharperpittam requested changes
Th component is missing a border around it.

Design
<img width="780" alt="image" src="https://github.com/ArdentHQ/dashbrd/assets/44671015/d2997b7c-f4c5-46fa-931e-e2f7595d1689">


Imp
<img width="212" alt="image" src="https://github.com/ArdentHQ/dashbrd/assets/44671015/97f12498-e606-4523-958c-389a3cd73e26">

2023-11-24 12:25 UTC, samharperpittam requested changes
Very unlikely scenario in the real world, but if a featured Collection just contains 1 NFT, the page isn't formatted correctly at 768 down

<img width="717" alt="image" src="https://github.com/ArdentHQ/dashbrd/assets/44671015/8acf09b2-252e-492a-9fa2-f205e197796c">

2023-11-24 12:32 UTC, samharperpittam requested changes
On mobile, the carousel can be different heights depending if a Collection description is displayed or not. Might be worth using a fixed height at all time. See video

https://github.com/ArdentHQ/dashbrd/assets/44671015/708f7295-2642-4ade-b3a9-70451addbd1d

2023-11-27 09:49 UTC, merged