feat: add collection vote table
ArdentHQ/dashbrd pull request #525
Opened 2023-11-30 18:41 UTC by shahin-hq

## Summary

## Checklist

-   [ ] I checked my UI changes against the design and there are no notable differences
-   [ ] I checked my UI changes for any responsiveness issues
-   [ ] I checked my (code) changes for obvious issues, debug statements and commented code
-   [ ] I opened a corresponding card on Clickup for any remaining TODOs in my code
-   [ ] I added a short description on how to test this PR _(if necessary)_
-   [ ] I added a storybook entry for the component that was added _(if necessary)_
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

2023-12-01 14:30 UTC, shahin-hq commented on resources/js/Pages/Collections/Components/CollectionOfTheMonth/CollectionOfTheMonth.tsx
Renamed these 3

2023-12-01 14:34 UTC, shahin-hq commented on resources/js/Pages/Collections/Components/CollectionOfTheMonth/index.tsx
Moved this to the `index` file, it is good to have this in the index file because of the layout.

2023-12-01 14:35 UTC, shahin-hq commented on resources/js/Pages/Collections/Components/CollectionVoting/VoteCollections.tsx
> +}
Dummy interface, should be linked with backend data

2023-12-01 15:24 UTC, alfonsobries reviewed
there is an issue with the spacing below the table, but that comes from the original branch (caused by the chart), will add a comment [on the ticket for the responsive version](https://app.clickup.com/t/86dqpcjgz) of the chart so can be handled there 
<img width="1417" alt="image" src="https://github.com/ArdentHQ/dashbrd/assets/17262776/e841368c-5260-4fa7-81cd-0dc43c9155fe">

2023-12-01 15:32 UTC, alfonsobries requested changes
There seems to be an issue with the vote height, (at least on mobile, didnt check the rest), design the height is 80px but implementation is 76px

<img width="652" alt="image" src="https://github.com/ArdentHQ/dashbrd/assets/17262776/b19e99da-12b2-4612-977e-b52c347d2dd0">

<img width="371" alt="image" src="https://github.com/ArdentHQ/dashbrd/assets/17262776/7cf251b7-cb21-4f3b-9236-07b64f179b7b">

2023-12-01 17:12 UTC, shahin-hq commented
@alfonsobries I fixed the `VotingCollection` item paddings, however, I'd not check it's height as there are some discrepancies in the design spec:

![image](https://github.com/ArdentHQ/dashbrd/assets/132887516/59351327-1e0e-49f8-98a5-6eef50c4f50e)

2023-12-04 13:59 UTC, crnkovic requested changes
It appears there is no transition or focus styles on rows in the table, plus there is some mismatch in the border around the image on dark mode:

Implementation:
![Screenshot 2023-12-04 at 14 57 23](https://github.com/ArdentHQ/dashbrd/assets/6536260/407a2dcf-f76d-488d-9853-407fb9a5d398)

Design:
![Screenshot 2023-12-04 at 14 58 21](https://github.com/ArdentHQ/dashbrd/assets/6536260/28cce263-3e32-4884-a587-ec43172936c5)

2023-12-05 09:01 UTC, ItsANameToo commented
small follow up in https://app.clickup.com/t/86dqqdr5p

2023-12-05 09:04 UTC, merged