refactor: searh nominatable collections
ArdentHQ/dashbrd pull request #545
Opened 2023-12-07 13:18 UTC by crnkovic

## Summary

## Checklist

-   [ ] I checked my UI changes against the design and there are no notable differences
-   [ ] I checked my UI changes for any responsiveness issues
-   [ ] I checked my (code) changes for obvious issues, debug statements and commented code
-   [ ] I opened a corresponding card on Clickup for any remaining TODOs in my code
-   [ ] I added a short description on how to test this PR _(if necessary)_
-   [ ] I added a storybook entry for the component that was added _(if necessary)_
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

2023-12-07 14:20 UTC, shahin-hq commented on resources/js/Pages/Collections/Components/CollectionVoting/NominationDialog.tsx
> +        }>(route("nominatable-collections", { query: debouncedQuery }));
Hey @crnkovic, I know it is in draft yet, I'd use `use-query` instead of axios, that would make it much easier.

2023-12-08 14:25 UTC, samharperpittam requested changes
This looks good other than 1 specific scenario where no results can be found. Currently missing the column titles which are shown in design. 

Also wondering if we should set the modal to be a specific height so it doesn't appear so squashed when no results are found? 

Design
<img width="547" alt="image" src="https://github.com/ArdentHQ/dashbrd/assets/44671015/2b88a516-1014-4deb-8384-1319c0cda59e">


Imp
<img width="848" alt="image" src="https://github.com/ArdentHQ/dashbrd/assets/44671015/3a9abed0-65a4-4e19-ab38-40e8d8ad4da3">

2023-12-12 01:44 UTC, oXtxNt9U commented
@crnkovic failing test

2023-12-12 09:44 UTC, ItsANameToo approved these changes

2023-12-12 09:44 UTC, merged