refactor: improve auth handling
ArdentHQ/dashbrd pull request #62
Opened 2023-09-08 09:29 UTC by shahin-hq

## Summary

## Checklist

-   [ ] I checked my UI changes against the design and there are no notable differences
-   [ ] I checked my UI changes for any responsiveness issues
-   [ ] I checked my (code) changes for obvious issues, debug statements and commented code
-   [ ] I opened a corresponding card on Clickup for any remaining TODOs in my code
-   [ ] I added a short description on how to test this PR _(if necessary)_
-   [ ] I added a storybook entry for the component that was added _(if necessary)_
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

2023-09-08 12:23 UTC, ItsANameToo reviewed
seems to work fine from what I tested @shahin-hq , nice approach

2023-09-15 10:50 UTC, ItsANameToo commented
awaiting #32

2023-09-21 10:28 UTC, ItsANameToo commented
this can be updated now that #32 is merged @shahin-hq

2023-09-22 12:58 UTC, shahin-hq commented on resources/js/Pages/Collections/Components/CollectionsFilter/CollectionsSorting.tsx
> +    const { t } = useTranslation();
React manages hooks by the call order, that is why I moved this call to the top of the component to prevent possible errors.

2023-09-25 08:55 UTC, samharperpittam requested changes
This PR looks good other than the Create Gallery issued described on Slack

2023-09-25 10:17 UTC, samharperpittam approved these changes

2023-09-25 10:58 UTC, ItsANameToo approved these changes

2023-09-25 10:58 UTC, merged