refactor: disable animation behind auth overlay
ArdentHQ/dashbrd pull request #74
Opened 2023-09-11 18:25 UTC by alfonsobries

## Summary

Closes https://app.clickup.com/t/865d20d27

## Checklist

-   [ ] I checked my UI changes against the design and there are no notable differences
-   [ ] I checked my UI changes for any responsiveness issues
-   [ ] I checked my (code) changes for obvious issues, debug statements and commented code
-   [ ] I opened a corresponding card on Clickup for any remaining TODOs in my code
-   [ ] I added a short description on how to test this PR _(if necessary)_
-   [ ] I added a storybook entry for the component that was added _(if necessary)_
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

2023-09-12 10:25 UTC, samharperpittam requested changes
If you navigate to `/wallet` as a guest user you can still see the pulse animation on the auth page there. Appreciated it may be unlikley that a user would navigate to that page seeing as Wallet is no longer a navbar item, but it might be worth fixing here too.

2023-09-13 10:18 UTC, ItsANameToo commented on resources/js/Components/Skeleton/Skeleton.tsx
> +    disabled?: boolean;
maybe we should rename this `animationDisabled` so it's clear what disabling does? 🤔

2023-09-13 10:19 UTC, samharperpittam approved these changes

2023-09-13 10:29 UTC, ItsANameToo commented
renamed, can you have another look @goga-m

2023-09-13 10:48 UTC, merged