refactor: nft details page
ArdentHQ/dashbrd pull request #90
Opened 2023-09-14 16:53 UTC by patricio0312rev

# [[nfts] Move NFT actions on the right side, remove items from image](https://app.clickup.com/t/861nam5mr)

## Summary

- NFT Details page has been refactored to match [our new designs in Figma file](https://www.figma.com/file/2Rr7zzoeGGiHYsROvfHaGe/Dashboard?type=design&node-id=21873-75966&mode=design&t=vcoRB84zBaBlwbiQ-0)

> **_NOTE:_**  Marketplace buttons are not in this ticket, they correspond to [[nfts] Add marketplace links to NFTs](https://app.clickup.com/t/861nam1a8)

## What changes are being made?

- `ParseIcon` can now receive `2xs` size for button icons.
- New components:
   - `NftOwner` to display the wallet that owns an NFT and the correct link to its own block explorer.
   - `NftActions` to contain the new action buttons, including the new `View NFT on` icon to redirect to the block explorer.
   - `NftBasicInfo` to contain the collection and NFT basic info.
- `NftImage` and `GalleryCard` components have been refactored to support these changes.
- When clicking an NFT image, it will open in a new tab.
- When hovering an NFT image, it will display the magnifying glass cursor.
- Actions are not on NFT image anymore. 
- Styles for various NFT view related components have been changed.
- New translations for each with copy changes for each new component.
- New unit tests for all these changes.

## How to reproduce

1. Run the app in `local` or `test_e2e` mode. Make sure you have a wallet with multiple collections and NFTs.
2. Go to `Collections` page.
3. Select any collection.
4. Select any NFT and see the magic ✨ 

## Views

- 320px:

<img width="737" alt="image" src="https://github.com/ArdentHQ/dashbrd/assets/55117912/cd1dfd86-bb69-410a-8b1d-44d24a8ab3c8">

- 640px:

<img width="726" alt="image" src="https://github.com/ArdentHQ/dashbrd/assets/55117912/92d6608f-a377-4dbc-aeea-b1c3be690eff">

- 768px:

<img width="655" alt="image" src="https://github.com/ArdentHQ/dashbrd/assets/55117912/2e25d200-5229-4546-a2a2-c1057b8c6920">

- 960px:

<img width="629" alt="image" src="https://github.com/ArdentHQ/dashbrd/assets/55117912/e094e2d5-2919-406f-85f7-8a0bef870baa">

- 1024px:

<img width="670" alt="image" src="https://github.com/ArdentHQ/dashbrd/assets/55117912/ffb51b5d-8bae-4a35-aaef-9d3465048e1e">

- 1280px:

<img width="1279" alt="image" src="https://github.com/ArdentHQ/dashbrd/assets/55117912/84feec86-ea86-4071-80e8-73b23f36b17e">

- 1440px and more:

<img width="1111" alt="image" src="https://github.com/ArdentHQ/dashbrd/assets/55117912/4f772400-7075-4e31-add2-e72875677bbc">

## Checklist

-   [ ] I checked my UI changes against the design and there are no notable differences
-   [ ] I checked my UI changes for any responsiveness issues
-   [ ] I checked my (code) changes for obvious issues, debug statements and commented code
-   [ ] I opened a corresponding card on Clickup for any remaining TODOs in my code
-   [ ] I added a short description on how to test this PR _(if necessary)_
-   [ ] I added a storybook entry for the component that was added _(if necessary)_
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

2023-09-18 10:13 UTC, ItsANameToo commented on resources/js/Components/ZoomDialog.test.tsx
> +import { ZoomDialog } from "./ZoomDialog";
is this used anywhere now? otherwise get rid of the component

2023-09-18 10:14 UTC, ItsANameToo commented on resources/js/Components/Collections/Nfts/NftHeader/NftActions.tsx
> +            case ExplorerChains.EthereumTestnet:
we have `goerli` for testnet, you should use that one for ETH testnet if you make a differentiation between polygon mainnet/testnet as well

2023-09-18 10:15 UTC, ItsANameToo commented on resources/js/Components/Collections/Nfts/NftHeader/NftActions.tsx
> +            case ExplorerChains.EthereumTestnet:
would handle testnet for eth + polygon here as well for the scan links

2023-09-18 10:15 UTC, ItsANameToo commented on resources/js/Components/Collections/Nfts/NftHeader/NftActions.tsx
> +            case ExplorerChains.EthereumTestnet:
while at it, also fix the goerli link as it should link to `https://goerli.etherscan.io/` and not to `goerli.polygonscan.com`

2023-09-18 10:16 UTC, ItsANameToo commented on resources/js/Components/Collections/Nfts/NftHeader/NftActions.tsx
> +        window.open(getChainLink(nft.collection.chainId, nft.collection.address, nft.tokenNumber), "_blank");
do we need this as a `window.open` or can we just add a link around the image that opens it in a new tab?

2023-09-18 10:18 UTC, ItsANameToo commented on resources/js/Components/Collections/Nfts/NftHeader/NftActions.tsx
> +            data-testid={"NftActions__container"}
all these icons need to be the color of the background

design:
<img width="539" alt="image" src="https://github.com/ArdentHQ/dashbrd/assets/35610748/8f26bea5-7cc1-45d6-9877-1ee41f47e19a">

implementation:
<img width="238" alt="image" src="https://github.com/ArdentHQ/dashbrd/assets/35610748/8ffed656-abf4-4d60-9162-1f24de3cf639">

2023-09-18 14:26 UTC, samharperpittam requested changes
@patricio0312rev  - At 960 down, the buttons have a grey background when they shouldn't.

Design
<img width="248" alt="image" src="https://github.com/ArdentHQ/dashbrd/assets/44671015/791d44de-ebce-4c2c-8b49-13f55ef2c73a">


Imp
<img width="362" alt="image" src="https://github.com/ArdentHQ/dashbrd/assets/44671015/222a058a-055d-4d5c-99c0-1a0386b18545">

2023-09-18 15:39 UTC, samharperpittam approved these changes

2023-09-19 07:56 UTC, ItsANameToo approved these changes

2023-09-19 07:56 UTC, merged