feat: new pagination design
ArdentHQ/dashbrd pull request #96
Opened 2023-09-15 16:34 UTC by patricio0312rev

# [[general] implement new pagination design](https://app.clickup.com/t/85ztypggv)

## Summary

- New pagination design has been implemented to match our figma files.

## Views

- 320px:

<img width="356" alt="image" src="https://github.com/ArdentHQ/dashbrd/assets/55117912/fd54e7fc-21a3-47f8-b2df-96f8a0012205">

- 640px:

<img width="634" alt="image" src="https://github.com/ArdentHQ/dashbrd/assets/55117912/0c41369a-b082-4dd9-9d9d-1aa3e4a4fd8f">

- 768px:

<img width="762" alt="image" src="https://github.com/ArdentHQ/dashbrd/assets/55117912/95739502-4dff-41bc-8aa6-bf0a21957002">

- 960px:

<img width="953" alt="image" src="https://github.com/ArdentHQ/dashbrd/assets/55117912/7dcce598-0121-4070-a3a9-e28aaa031244">

- 1024px:

<img width="1009" alt="image" src="https://github.com/ArdentHQ/dashbrd/assets/55117912/1241902f-d638-45e0-a785-274fdd6d93d8">

- 1280px:

<img width="1269" alt="image" src="https://github.com/ArdentHQ/dashbrd/assets/55117912/d8000c1b-b695-40c5-bd0b-ad817488b279">

- 1440px and more:

<img width="1427" alt="image" src="https://github.com/ArdentHQ/dashbrd/assets/55117912/3a339ee5-b32e-49de-8205-a558aa6baa17">

## Checklist

-   [ ] I checked my UI changes against the design and there are no notable differences
-   [ ] I checked my UI changes for any responsiveness issues
-   [ ] I checked my (code) changes for obvious issues, debug statements and commented code
-   [ ] I opened a corresponding card on Clickup for any remaining TODOs in my code
-   [ ] I added a short description on how to test this PR _(if necessary)_
-   [ ] I added a storybook entry for the component that was added _(if necessary)_
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

2023-09-19 11:29 UTC, ItsANameToo requested changes
some issues UI wise:
- pagination icons should be 12x12, they are currently 16x16
- the page limit dropdown is very small, it should be as wide as the entry itself
impl:
<img width="258" alt="image" src="https://github.com/ArdentHQ/dashbrd/assets/35610748/491c2503-fee4-4226-89f9-e24a596f9cc4">

design:
<img width="404" alt="image" src="https://github.com/ArdentHQ/dashbrd/assets/35610748/8851f461-f7cd-4525-9dc3-9164ad59ed18">
- search close button on desktop gets squashed. Also the search input should be larger and show placeholder by default instead of the page
<img width="191" alt="image" src="https://github.com/ArdentHQ/dashbrd/assets/35610748/75c77e64-4fec-46be-9aa0-a39a48adf39e">
- when opening the search on desktop, the entire pagination row moves down slightly
- on mobile the prev/next etc buttons are inconsistent when they appear and not in line with design. They currently hide the first/prev buttons on page 1, but on the last page it should hide both next/last buttons and it only hides the "last" button
- between 375 and above the pagination does not always fit
<img width="653" alt="image" src="https://github.com/ArdentHQ/dashbrd/assets/35610748/da7afb37-efb1-4895-8ce3-cce19bcf2ba5">
- on 375 and below, the search should not open where the page number is but below it instead (to replace the navigation items)
design:
<img width="323" alt="image" src="https://github.com/ArdentHQ/dashbrd/assets/35610748/5faa0fde-0c41-4c7d-b56f-425287e4c9cc">

2023-09-22 10:29 UTC, samharperpittam requested changes
At breakpoint 640, the pagination should be the mobile variant.

Design
<img width="705" alt="image" src="https://github.com/ArdentHQ/dashbrd/assets/44671015/b0f3430d-7932-44e3-8528-85eaf8831c8b">


Implementation
<img width="891" alt="image" src="https://github.com/ArdentHQ/dashbrd/assets/44671015/7f3e11b0-dc0e-4db9-bc7d-7321e8a5e272">

---

On desktop when clicking the 3 dots to enter a page number, the search field is incredibly small.

Design
<img width="503" alt="image" src="https://github.com/ArdentHQ/dashbrd/assets/44671015/f22e4568-3199-4f7e-b2b5-a669f288c16b">


Implementation
<img width="262" alt="image" src="https://github.com/ArdentHQ/dashbrd/assets/44671015/99ed1d8e-c248-4b4c-adcd-260476dfa5c7">

2023-09-22 12:23 UTC, samharperpittam requested changes
At 640, is there a reason why the numeric dropdown doesn't display the text `Items`?
<img width="255" alt="image" src="https://github.com/ArdentHQ/dashbrd/assets/44671015/83c720f7-efbd-4990-8dbf-0c6a8698660c">

2023-09-22 12:25 UTC, samharperpittam requested changes
Also, is it possible to modify this so the mobile view starts at 375 down instead of 320 please?

<img width="491" alt="image" src="https://github.com/ArdentHQ/dashbrd/assets/44671015/a68b6955-9dc0-4297-9bf1-119421e9be87">

Edit: can ignore this comment.

2023-09-22 12:58 UTC, samharperpittam approved these changes

2023-09-22 13:20 UTC, samharperpittam approved these changes

2023-09-22 13:27 UTC, ItsANameToo commented on resources/js/Components/Pagination/SelectPageLimit.tsx
> +            className="w-full xs:w-[12rem] sm:flex sm:justify-between"
```suggestion
            className="w-full xs:w-48 sm:flex sm:justify-between"
```

2023-09-22 13:29 UTC, ItsANameToo commented on resources/js/Components/Pagination/PreviousPageLink.tsx
> +        disabled={href == null}
```suggestion
        disabled={href === null}
```

2023-09-22 13:29 UTC, ItsANameToo commented on resources/js/Components/Pagination/Pagination.tsx
> +            className="!m-0 w-full sm:w-fit"
why did it need the `!` for the margin?

2023-09-28 10:43 UTC, ItsANameToo approved these changes

2023-09-28 10:58 UTC, merged